version: '3'

services:
  db:
    image: postgres:10.2
    ports:
      - "5432:5432"
  web:
    environment:
      - HOST_DB=db
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
