version: '3'

services:
  db:
    image: postgres:10.2
    ports:
      - "5432:5432"
  nodejs:
    image: node:8.9.4
    command: bash -c "npm i && npm run build"
    volumes:
      - ./frontend/render-ai-app:/front_end
    working_dir: /front_end
  web:
    environment:
      - HOST_DB=db
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "nodejs"

