version: '3'

services:
  nginx:
    image: nginx:1.13
    restart: always
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/
      - ./frontend/render-ai-app/dist:/front_end
    ports:
      - "8001:8000"
    depends_on:
      - "web"
  db:
    image: postgres:10.2
    ports:
      - "5432:5432"
  nodejs:
    image: node:8.9.4
    command: bash -c "npm i && npm run build"
    volumes:
      - ./frontend/render-ai-app:/front_end
    working_dir: /front_end
  web:
    environment:
      - HOST_DB=db
    build: .
    command: bash -c "python3 manage.py migrate && uwsgi --plugin python --ini /conf/uwsgi.ini"
    volumes:
      - .:/code
      - ./conf/uwsgi:/conf
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "nodejs"

