# Generated by Django 2.0.2 on 2018-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mldata',
            name='key_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
