# Generated by Django 2.0.2 on 2018-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0001_initial'),
        ('ml_data_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mldata',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mldata',
            unique_together={('company', 'name')},
        ),
    ]
