# Generated by Django 2.0.2 on 2018-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mldata',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
