# Generated by Django 2.0.2 on 2018-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data_care', '0002_mldata_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mldata',
            name='customer_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
