# Generated by Django 2.0.2 on 2018-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data_care', '0002_mldata_key_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mldata',
            name='key_data',
            field=models.TextField(blank=True),
        ),
    ]
