# Generated by Django 2.0.2 on 2018-03-02 08:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_data_care', '0003_auto_20180302_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mldata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
